# Generated by Django 2.2.6 on 2019-11-28 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblDaily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblID', models.PositiveIntegerField()),
                ('date', models.DateField(null=True)),
                ('totalGame', models.PositiveIntegerField()),
                ('playerNum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tblID', models.IntegerField()),
                ('thresholdPtn', models.CharField(blank=True, default='', max_length=50)),
                ('dispTblName', models.CharField(blank=True, default='', max_length=50)),
                ('startPeriod', models.DateField(null=True)),
                ('endPeriod', models.DateField(null=True)),
                ('hideLastMonth', models.BooleanField(default=False)),
                ('rvNum', models.IntegerField()),
                ('chNum', models.IntegerField()),
                ('event1name', models.CharField(blank=True, default='', max_length=50)),
                ('event2name', models.CharField(blank=True, default='', max_length=50)),
                ('event3name', models.CharField(blank=True, default='', max_length=50)),
                ('event4name', models.CharField(blank=True, default='', max_length=50)),
                ('event5name', models.CharField(blank=True, default='', max_length=50)),
                ('event6name', models.CharField(blank=True, default='', max_length=50)),
                ('event7name', models.CharField(blank=True, default='', max_length=50)),
                ('event8name', models.CharField(blank=True, default='', max_length=50)),
                ('comment', models.CharField(blank=True, default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TblMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playerID', models.PositiveIntegerField()),
                ('name', models.CharField(blank=True, default='', max_length=20)),
                ('dispName', models.CharField(blank=True, default='', max_length=20)),
                ('inputName1', models.CharField(blank=True, default='', max_length=20)),
                ('inputName2', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TblRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameNum', models.PositiveIntegerField()),
                ('gamePt', models.FloatField()),
                ('gross', models.FloatField()),
                ('HDCP', models.FloatField()),
                ('playerID', models.PositiveIntegerField(null=True)),
                ('net', models.FloatField()),
                ('winNum', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TblScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('gameNo', models.PositiveIntegerField(null=True)),
                ('gamePt', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('playerID', models.PositiveIntegerField(null=True)),
                ('pairID', models.PositiveIntegerField(null=True)),
                ('row', models.PositiveIntegerField(default=0, null=True)),
                ('serve1st', models.PositiveIntegerField(null=True)),
                ('serve2nd', models.PositiveIntegerField(null=True)),
                ('serveTurn', models.PositiveIntegerField(default=0, null=True)),
                ('temp', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TblPeriodData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HDCP', models.FloatField(null=True)),
                ('event1', models.IntegerField(null=True)),
                ('event2', models.IntegerField(null=True)),
                ('event3', models.IntegerField(null=True)),
                ('event4', models.IntegerField(null=True)),
                ('event5', models.IntegerField(null=True)),
                ('event6', models.IntegerField(null=True)),
                ('event7', models.IntegerField(null=True)),
                ('event8', models.IntegerField(null=True)),
                ('adjustDate', models.IntegerField(null=True)),
                ('playerID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='score.TblMember')),
                ('tblID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.TblManage')),
            ],
        ),
    ]
